### ISSUE TITLE
Potential divide by zero  should be wrapped in a Try Except block

### ISSUE THREAD

**Issue by seanrivera** [nasa-jpl/osr-rover-code#65]
Depending on the setting's wheel distance you can cause a divide by zero error when updating position, breaking the normal joystick behavior. This can be easily remedied with a Try-Catch block or a check for equality
https://github.com/nasa-jpl/osr-rover-code/blob/e26ef24b28ad5f313e4af9e9ec70c7c9cdceac79/ROS/osr/scripts/robot.py#L128-L129

**Comment by ericjunkins** [comment]
This issue is noted, will be solved shortly in a PR that will update the structure of how the robot calculates things. @Achllle has done quite a bit of work overhauling the code, you can check out some of his work at https://github.com/Achllle/osr-rover-code but we are working to get these integrated as soon as we can
